using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using System.Data.OleDb;
using System.IO;
using System.Collections;
using System.Data.SqlClient;
using System.Runtime.InteropServices;
using System.Threading;
using System.Globalization;



namespace UserAutherization
{
    class Registration
    {
        Registration4 R4 = new Registration4();
        public static string ConnectionString;
        public void setConnectionString()
        {
            clsDataAccess objclsDataAccess = new clsDataAccess();
            ConnectionString = objclsDataAccess.StrConectionStringLocal;
        }

        //this method return a get a computer name from the system
        [DllImport("kernel32.dll")]
        static extern bool GetComputerName(StringBuilder name, ref ulong size);
        public string SerialNO = "";
        public string CompanyName = "";
        public string TotalNO = "";
        public string srcString = "";
        public string a1 = "";
        public string no1 = "";
        public string no2 = "";
        public string no3 = ""; 
        public string no4 = "";
        public string no5 = "";
        public string no6 = "";
        public string no7 = "";
        public string no8 = "";
        public string no9 = "";
        public string no10 = "";
        public string finalserial = "";
        public string ComputerName = "";
        public string AutorizeCode = "";
        public static ArrayList UserAccess1 = new ArrayList();
        public string First2cFromCN = "";
        public string First2cFromCompanyName = "";
        public string TempTotalNO = "";
        public string RegPart1 = "";
        public string RegPart2 = "";
        public string RegNO = "";
        public string CheckR1 = "";
        public string CheckR2 = "";
        public string CheckR3 = "";
        public string CheckR4 = "";
        public string CheckR5 = "";
        public string CheckR6 = "";
        public string RegCode1 = "";
        public string RegCode2 = "";
        public string RegCode3 = "";
        public string RegCode4 = "";
        public string RegCode5 = "";
        public string RegCode6 = "";
        public  string finalRegNumber="";

        public string ftest1 = "";
        public string ftest2= "";
        public string ftest3 = "";
        public string ftest4 = "";
        public string ftest5 = "";
        public string ftest6 = "";
        public string ftest7 = "";
        public string ftest8 = "";
        public string ftest9 = "";
        public string ftest10 = "";


        public string CompanyName1 = ""; 
        public string  SerialNumber1 = "";

        public string RegisterCode = "";
        public string seNO = "";

        

       
    
        [STAThread]
        public void Getname(string name1)
        {
            try
            {
                // R4.GeSerialNO(); 
                //get company name and serial number from the class Registration4.cs
                //when run the registration process user may enter these
                // SerialNO = R4.GeSerialNO();

                //SerialNO = R4.GeSerialNO();
                //CompanyName = R4.GetCompanyName();

                Get_Company_Name1();// this method get the company name and serial number where user has entered
                SerialNO = SerialNumber1;
                CompanyName = CompanyName1;


                //following code segment get the computerName from the computer
                ulong size = 256;
                StringBuilder name = new StringBuilder((int)size);
                bool success = GetComputerName(name, ref size);

                //computer name assign to string variable called ComputerName
                ComputerName = name + "";
                First2cFromCN = ComputerName.Substring(0, 2);
                //ftest1 = First2cFromCN.Substring(0, 1);
                //ftest2 = First2cFromCN.Substring(1, 1);
                //if(ftest1=="2A" ||ftest1=="2B" ||ftest1=="2C" || ftest1=="2D" || ftest1=="2E" || ftest1=="2F" || ftest1=="3A" || ftest1=="3B" || ftest1=="3C" || ftest1=="3E" || ftest1=="3D" || ftest1=="3E"|| ftest1=="3F" || ftest1=="4A" || ftest1=="4B" || ftest1=="4C" || ftest1=="4D" || ftest1=="4E" || ftest1=="4F" || ftest1=="2F" || ftest1=="5A" || ftest1=="5B" || ftest1=="5C" || ftest1=="2D"|| ftest1=="5E" || ftest1=="5F" || ftest1=="6A" || ftest1=="6B" || ftest1=="6C" || ftest1=="6D" || ftest1=="6E" || ftest1=="6F" || ftest1=="7A" || ftest1=="7B" || ftest1=="7C" || ftest1=="7D" || ftest1=="7E" || ftest1=="7F")


                //following methods retirew company name and register number from the databae 
                //these numbers are generated by the installation program

                //Get_Company_Name();//coment temparory 

                //part of the serial number is making using computername and the 
                //registrationcode that we are taking from the database
                First2cFromCompanyName = CompanyName.Substring(0, 3);

                // SerialNO = name + AutorizeCode;
                TotalNO = SerialNO + CompanyName;
                //SerialNO-entered by client 
                TempTotalNO = First2cFromCN + SerialNO + First2cFromCompanyName;

                //00ur given code contain 5characters
                srcString = TempTotalNO;//this is the temp number we make using first 2 letters from the cimputername and our givent 
                //serialno andfirst4 letters from company name


                //getting the ascii code of our defined serial number
                byte[] asciiString = Encoding.ASCII.GetBytes(srcString);
                // MessageBox.Show(BitConverter.ToString(asciiString));
                a1 = (BitConverter.ToString(asciiString));// this is contain the ascii value seperating by hypend

                ftest1 = a1.Substring(0, 2);
                ftest2 = a1.Substring(3, 2);
                ftest3 = a1.Substring(6, 2);
                ftest4 = a1.Substring(9, 2);
                ftest5 = a1.Substring(12, 2);
                ftest6 = a1.Substring(15, 2);
                ftest7 = a1.Substring(18, 2);
                ftest8 = a1.Substring(21, 2);
                ftest9 = a1.Substring(24, 2);
                ftest10 = a1.Substring(27, 2);



                //...................
                if (ftest1 == "2A" || ftest1 == "2B" || ftest1 == "2C" || ftest1 == "2D" || ftest1 == "2E" || ftest1 == "2F" || ftest1 == "3A" || ftest1 == "3B" || ftest1 == "3C" || ftest1 == "3D" || ftest1 == "3E" || ftest1 == "3F" || ftest1 == "4A" || ftest1 == "4B" || ftest1 == "4C" || ftest1 == "4D" || ftest1 == "4E" || ftest1 == "4F" || ftest1 == "2F" || ftest1 == "5A" || ftest1 == "5B" || ftest1 == "5C" || ftest1 == "2D" || ftest1 == "5E" || ftest1 == "5F" || ftest1 == "6A" || ftest1 == "6B" || ftest1 == "6C" || ftest1 == "6D" || ftest1 == "6E" || ftest1 == "6F" || ftest1 == "7A" || ftest1 == "7B" || ftest1 == "7C" || ftest1 == "7D" || ftest1 == "7E" || ftest1 == "7F")
                {
                    ftest1 = "80";

                }

                if (ftest2 == "2A" || ftest2 == "2B" || ftest2 == "2C" || ftest2 == "2D" || ftest2 == "2E" || ftest2 == "2F" || ftest2 == "3A" || ftest2 == "3B" || ftest2 == "3C" || ftest2 == "3D" || ftest2 == "3E" || ftest2 == "3F" || ftest2 == "4A" || ftest2 == "4B" || ftest2 == "4C" || ftest2 == "4D" || ftest2 == "4E" || ftest2 == "4F" || ftest2 == "2F" || ftest2 == "5A" || ftest2 == "5B" || ftest2 == "5C" || ftest2 == "2D" || ftest2 == "5E" || ftest2 == "5F" || ftest2 == "6A" || ftest2 == "6B" || ftest2 == "6C" || ftest2 == "6D" || ftest2 == "6E" || ftest2 == "6F" || ftest2 == "7A" || ftest2 == "7B" || ftest2 == "7C" || ftest2 == "7D" || ftest2 == "7E" || ftest2 == "7F")
                {
                    ftest2 = "81";

                }


                if (ftest3 == "2A" || ftest3 == "2B" || ftest3 == "2C" || ftest3 == "2D" || ftest3 == "2E" || ftest3 == "2F" || ftest3 == "3A" || ftest3 == "3B" || ftest3 == "3C" || ftest3 == "3D" || ftest3 == "3E" || ftest3 == "3F" || ftest3 == "4A" || ftest3 == "4B" || ftest3 == "4C" || ftest3 == "4D" || ftest3 == "4E" || ftest3 == "4F" || ftest3 == "2F" || ftest3 == "5A" || ftest3 == "5B" || ftest3 == "5C" || ftest3 == "2D" || ftest3 == "5E" || ftest3 == "5F" || ftest3 == "6A" || ftest3 == "6B" || ftest3 == "6C" || ftest3 == "6D" || ftest3 == "6E" || ftest3 == "6F" || ftest3 == "7A" || ftest3 == "7B" || ftest3 == "7C" || ftest3 == "7D" || ftest3 == "7E" || ftest3 == "7F")
                {
                    ftest3 = "82";

                }

                if (ftest4 == "2A" || ftest4 == "2B" || ftest4 == "2C" || ftest4 == "2D" || ftest4 == "2E" || ftest4 == "2F" || ftest4 == "3A" || ftest4 == "3B" || ftest4 == "3C" || ftest4 == "3D" || ftest4 == "3E" || ftest4 == "3F" || ftest4 == "4A" || ftest4 == "4B" || ftest4 == "4C" || ftest4 == "4D" || ftest4 == "4E" || ftest4 == "4F" || ftest4 == "2F" || ftest4 == "5A" || ftest4 == "5B" || ftest4 == "5C" || ftest4 == "2D" || ftest4 == "5E" || ftest4 == "5F" || ftest4 == "6A" || ftest4 == "6B" || ftest4 == "6C" || ftest4 == "6D" || ftest4 == "6E" || ftest4 == "6F" || ftest4 == "7A" || ftest4 == "7B" || ftest4 == "7C" || ftest4 == "7D" || ftest4 == "7E" || ftest4 == "7F")
                {
                    ftest4 = "83";

                }

                if (ftest5 == "2A" || ftest5 == "2B" || ftest5 == "2C" || ftest5 == "2D" || ftest5 == "2E" || ftest5 == "2F" || ftest5 == "3A" || ftest5 == "3B" || ftest5 == "3C" || ftest5 == "3D" || ftest5 == "3E" || ftest5 == "3F" || ftest5 == "4A" || ftest5 == "4B" || ftest5 == "4C" || ftest5 == "4D" || ftest5 == "4E" || ftest5 == "4F" || ftest5 == "2F" || ftest5 == "5A" || ftest5 == "5B" || ftest5 == "5C" || ftest5 == "2D" || ftest5 == "5E" || ftest5 == "5F" || ftest5 == "6A" || ftest5 == "6B" || ftest5 == "6C" || ftest5 == "6D" || ftest5 == "6E" || ftest5 == "6F" || ftest5 == "7A" || ftest5 == "7B" || ftest5 == "7C" || ftest5 == "7D" || ftest5 == "7E" || ftest5 == "7F")
                {
                    ftest5 = "84";

                }


                if (ftest6 == "2A" || ftest6 == "2B" || ftest6 == "2C" || ftest6 == "2D" || ftest6 == "2E" || ftest6 == "2F" || ftest6 == "3A" || ftest6 == "3B" || ftest6 == "3C" || ftest6 == "3D" || ftest6 == "3E" || ftest6 == "3F" || ftest6 == "4A" || ftest6 == "4B" || ftest6 == "4C" || ftest6 == "4D" || ftest6 == "4E" || ftest6 == "4F" || ftest6 == "2F" || ftest6 == "5A" || ftest6 == "5B" || ftest6 == "5C" || ftest6 == "2D" || ftest6 == "5E" || ftest6 == "5F" || ftest6 == "6A" || ftest6 == "6B" || ftest5 == "6C" || ftest6 == "6D" || ftest6 == "6E" || ftest6 == "6F" || ftest6 == "7A" || ftest6 == "7B" || ftest6 == "7C" || ftest6 == "7D" || ftest6 == "7E" || ftest6 == "7F")
                {
                    ftest6 = "85";

                }

                if (ftest7 == "2A" || ftest7 == "2B" || ftest7 == "2C" || ftest7 == "2D" || ftest7 == "2E" || ftest7 == "2F" || ftest7 == "3A" || ftest6 == "3B" || ftest7 == "3C" || ftest7 == "3D" || ftest7 == "3E" || ftest7 == "3F" || ftest7 == "4A" || ftest7 == "4B" || ftest7 == "4C" || ftest7 == "4D" || ftest7 == "4E" || ftest7 == "4F" || ftest7 == "2F" || ftest7 == "5A" || ftest7 == "5B" || ftest7 == "5C" || ftest7 == "2D" || ftest7 == "5E" || ftest7 == "5F" || ftest7 == "6A" || ftest7 == "6B" || ftest7 == "6C" || ftest7 == "6D" || ftest7 == "6E" || ftest7 == "6F" || ftest7 == "7A" || ftest7 == "7B" || ftest7 == "7C" || ftest7 == "7D" || ftest7 == "7E" || ftest7 == "7F")
                {
                    ftest7 = "86";

                }


                if (ftest8 == "2A" || ftest8 == "2B" || ftest8 == "2C" || ftest8 == "2D" || ftest8 == "2E" || ftest8 == "2F" || ftest8 == "3A" || ftest8 == "3B" || ftest8 == "3C" || ftest8 == "3D" || ftest8 == "3E" || ftest8 == "3F" || ftest8 == "4A" || ftest8 == "4B" || ftest8 == "4C" || ftest8 == "4D" || ftest8 == "4E" || ftest8 == "4F" || ftest8 == "2F" || ftest8 == "5A" || ftest8 == "5B" || ftest8 == "5C" || ftest8 == "2D" || ftest8 == "5E" || ftest8 == "5F" || ftest8 == "6A" || ftest8 == "6B" || ftest8 == "6C" || ftest8 == "6D" || ftest8 == "6E" || ftest8 == "6F" || ftest8 == "7A" || ftest8 == "7B" || ftest8 == "7C" || ftest8 == "7D" || ftest8 == "7E" || ftest8 == "7F")
                {
                    ftest8 = "87";

                }


                if (ftest9 == "2A" || ftest9 == "2B" || ftest9 == "2C" || ftest9 == "2D" || ftest9 == "2E" || ftest9 == "2F" || ftest9 == "3A" || ftest9 == "3B" || ftest9 == "3C" || ftest9 == "3D" || ftest9 == "3E" || ftest9 == "3F" || ftest9 == "4A" || ftest9 == "4B" || ftest9 == "4C" || ftest9 == "4D" || ftest9 == "4E" || ftest9 == "4F" || ftest9 == "2F" || ftest9 == "5A" || ftest9 == "5B" || ftest9 == "5C" || ftest9 == "2D" || ftest9 == "5E" || ftest9 == "5F" || ftest9 == "6A" || ftest9 == "6B" || ftest9 == "6C" || ftest9 == "6D" || ftest9 == "6E" || ftest9 == "6F" || ftest9 == "7A" || ftest9 == "7B" || ftest9 == "7C" || ftest9 == "7D" || ftest9 == "7E" || ftest9 == "7F")
                {
                    ftest9 = "88";

                }


                if (ftest10 == "2A" || ftest10 == "2B" || ftest10 == "2C" || ftest10 == "2D" || ftest10 == "2E" || ftest10 == "2F" || ftest10 == "3A" || ftest10 == "3B" || ftest10 == "3C" || ftest10 == "3D" || ftest10 == "3E" || ftest10 == "3F" || ftest10 == "4A" || ftest10 == "4B" || ftest10 == "4C" || ftest10 == "4D" || ftest10 == "4E" || ftest10 == "4F" || ftest10 == "2F" || ftest10 == "5A" || ftest10 == "5B" || ftest10 == "5C" || ftest10 == "2D" || ftest10 == "5E" || ftest10 == "5F" || ftest10 == "6A" || ftest10 == "6B" || ftest10 == "6C" || ftest10 == "6D" || ftest10 == "6E" || ftest10 == "6F" || ftest10 == "7A" || ftest10 == "7B" || ftest10 == "7C" || ftest10 == "7D" || ftest10 == "7E" || ftest10 == "7F")
                {
                    ftest10 = "89";

                }
                //......................
                no1 = ftest1;
                no2 = ftest2;
                no3 = ftest3;
                no4 = ftest4;
                no5 = ftest5;
                no6 = ftest6;
                no7 = ftest7;
                no8 = ftest8;
                no9 = ftest9;
                no10 = ftest10;

                //making final serial number which is only contain digits
                finalserial = no1 + no2 + no3 + no4 + no5 + no6 + no7 + no8 + no9 + no10;
                //finalserial = no1 + no2 + no3 + no4 + no5 + no6 + no7 + no8 + no9 + no10;
                RegPart1 = finalserial.Substring(0, 3);
                RegPart2 = finalserial.Substring(17, 3);
                RegNO = RegPart1 + RegPart2;//THIS IS THE NUMBER customer should send to us and accoding to this number 
                // we are generating registration code



                //firstcode part
                CheckR1 = RegPart1.Substring(0, 1);
                if (CheckR1 == " 0") { RegCode1 = "QVCD"; }
                else if (CheckR1 == "1") { RegCode1 = "KQRD"; }
                else if (CheckR1 == "2") { RegCode1 = "GWZQ"; }
                else if (CheckR1 == "3") { RegCode1 = "TZYZ"; }
                else if (CheckR1 == "4") { RegCode1 = "MZKQ"; }
                else if (CheckR1 == "5") { RegCode1 = "MFAQ"; }
                else if (CheckR1 == "6") { RegCode1 = "LZBN"; }
                else if (CheckR1 == "7") { RegCode1 = "ZBKB"; }
                else if (CheckR1 == "8") { RegCode1 = "WZBN"; }
                else if (CheckR1 == "9") { RegCode1 = "AQPQ"; }
                else { RegCode1 = "ABDQ"; }


                //second codepart

                CheckR2 = RegPart1.Substring(1, 1);
                if (CheckR2 == " 0") { RegCode2 = "QVCD"; }
                else if (CheckR2 == "1") { RegCode2 = "KQRD"; }
                else if (CheckR2 == "2") { RegCode2 = "GWZQ"; }
                else if (CheckR2 == "3") { RegCode2 = "TZYZ"; }
                else if (CheckR2 == "4") { RegCode2 = "MZKQ"; }
                else if (CheckR2 == "5") { RegCode2 = "MFAQ"; }
                else if (CheckR2 == "6") { RegCode2 = "LZBN"; }
                else if (CheckR2 == "7") { RegCode2 = "ZBKB"; }
                else if (CheckR2 == "8") { RegCode2 = "WZBN"; }
                else if (CheckR1 == "9") { RegCode2 = "AQPQ"; }
                else { RegCode2 = "ABDQ"; }

                //third part

                CheckR3 = RegPart1.Substring(2, 1);
                if (CheckR2 == " 0") { RegCode1 = "QVCD"; }
                else if (CheckR3 == "1") { RegCode3 = "KQRD"; }
                else if (CheckR3 == "2") { RegCode3 = "GWZQ"; }
                else if (CheckR3 == "3") { RegCode3 = "TZYZ"; }
                else if (CheckR3 == "4") { RegCode3 = "MZKQ"; }
                else if (CheckR3 == "5") { RegCode3 = "MFAQ"; }
                else if (CheckR3 == "6") { RegCode3 = "LZBN"; }
                else if (CheckR3 == "7") { RegCode3 = "ZBKB"; }
                else if (CheckR3 == "8") { RegCode3 = "WZBN"; }
                else if (CheckR3 == "9") { RegCode3 = "AQPQ"; }
                else { RegCode3 = "ABDQ"; }

                //forth part

                CheckR4 = RegPart2.Substring(0, 1);
                if (CheckR4 == "0") { RegCode1 = "QVCD"; }
                else if (CheckR4 == "1") { RegCode4 = "KQRD"; }
                else if (CheckR4 == "2") { RegCode4 = "GWZQ"; }
                else if (CheckR4 == "3") { RegCode4 = "TZYZ"; }
                else if (CheckR4 == "4") { RegCode4 = "MZKQ"; }
                else if (CheckR4 == "5") { RegCode4 = "MFAQ"; }
                else if (CheckR4 == "6") { RegCode4 = "LZBN"; }
                else if (CheckR4 == "7") { RegCode4 = "ZBKB"; }
                else if (CheckR4 == "8") { RegCode4 = "WZBN"; }
                else if (CheckR4 == "9") { RegCode4 = "AQPQ"; }
                else { RegCode4 = "ABDQ"; }

                //fifth part

                CheckR5 = RegPart2.Substring(1, 1);
                if (CheckR4 == "0") { RegCode5 = "QVCD"; }
                else if (CheckR5 == "1") { RegCode5 = "KQRD"; }
                else if (CheckR5 == "2") { RegCode5 = "GWZQ"; }
                else if (CheckR5 == "3") { RegCode5 = "TZYZ"; }
                else if (CheckR5 == "4") { RegCode5 = "MZKQ"; }
                else if (CheckR5 == "5") { RegCode5 = "MFAQ"; }
                else if (CheckR5 == "6") { RegCode5 = "LZBN"; }
                else if (CheckR5 == "7") { RegCode5 = "ZBKB"; }
                else if (CheckR5 == "8") { RegCode5 = "WZBN"; }
                else if (CheckR5 == "9") { RegCode5 = "AQPQ"; }
                else { RegCode5 = "ABDQ"; }

                //sisth part

                CheckR6 = RegPart2.Substring(2, 1);
                if (CheckR6 == "0") { RegCode6 = "QVCD"; }
                else if (CheckR6 == "1") { RegCode6 = "KQRD"; }
                else if (CheckR6 == "2") { RegCode6 = "GWZQ"; }
                else if (CheckR6 == "3") { RegCode6 = "TZYZ"; }
                else if (CheckR6 == "4") { RegCode6 = "MZKQ"; }
                else if (CheckR6 == "5") { RegCode6 = "MFAQ"; }
                else if (CheckR6 == "6") { RegCode6 = "LZBN"; }
                else if (CheckR6 == "7") { RegCode6 = "ZBKB"; }
                else if (CheckR6 == "8") { RegCode6 = "WZBN"; }
                else if (CheckR6 == "9") { RegCode6 = "AQPQ"; }
                else { RegCode6 = "ABDQ"; }



                finalRegNumber = RegCode1 + RegCode2 + RegCode3 + RegCode4 + RegCode5 + RegCode6;

                //MessageBox.Show(finalRegNumber); // this the serial number we are generatimg through our process
                DeleteRT();
                RegisterCode = finalRegNumber;
                seNO = RegNO;//this is the final serial number genrate by the program
                UpdateRegCode(RegisterCode, seNO);

                //inser computername and serialnumber(which is going to be use to generate product key
                UpdateComputerName(ComputerName, RegNO);
                //DeleteRT();
            }
            catch //(Exception ex)
            {
               // MessageBox.Show("Enter Valid Fomat of Data");
               // R4.btnNext.Focus();
            }

        }


        public string fRegcode = "";
        public string GetfinalRegCode()
        {
            fRegcode = finalRegNumber;
            return fRegcode;
        }


        #region Update_ComputerName
        public void UpdateComputerName(string Computer_Name, string NumericValue)
        {
            setConnectionString();
            try
            {
                string ConnString = ConnectionString;// @"Provider=Microsoft.Jet.OLEDB.4.0;Data Source=ImportCosting.mdb";
                SqlConnection Conn = new SqlConnection(ConnString);
                SqlCommand cmd = Conn.CreateCommand();
                cmd.CommandText = "INSERT INTO RegCodeGen (ComputerName,NumericValue) VALUES ('" + Computer_Name + "','" + NumericValue + "')";
                // "INSERT INTO SalesOrder(SONO) VALUES('" + SONO + "')";
                Conn.Open();
                cmd.ExecuteNonQuery();
                Conn.Close();
            }
            catch
            { }
        }
        #endregion
        // update the registration code

        #region UpdateRegCode
        public void UpdateRegCode(string RegisterCode, string seNO)
        {
            setConnectionString();
            try
            {
                string ConnString = ConnectionString;// @"Provider=Microsoft.Jet.OLEDB.4.0;Data Source=ImportCosting.mdb";
                SqlConnection Conn = new SqlConnection(ConnString);
                SqlCommand cmd = Conn.CreateCommand();
                cmd.CommandText = "INSERT INTO RT(RegCode,SerialNumber) VALUES ('" + RegisterCode + "','" + seNO + "')";
               // "INSERT INTO RegCodeGen (ComputerName,NumericValue) VALUES ('" + RegisterCode + "','" + NumericValue + "')";
                // "INSERT INTO SalesOrder(SONO) VALUES('" + SONO + "')";
                Conn.Open();
                cmd.ExecuteNonQuery();
                Conn.Close();
            }
            catch
            { }
        }
        #endregion




        //.....................


        //...........................................


        #region Dlete RT
        public void DeleteRT()
        {
            setConnectionString();
            try
            {
                string ConnString = ConnectionString;// @"Provider=Microsoft.Jet.OLEDB.4.0;Data Source=ImportCosting.mdb";
                SqlConnection Conn = new SqlConnection(ConnString);
                SqlCommand cmd = Conn.CreateCommand();
                //cmd.CommandText = "INSERT INTO RT(RegCode,SerialNumber) VALUES ('" + RegisterCode + "','" + seNO + "')";
                cmd.CommandText = "Delete RT";
                // "INSERT INTO RegCodeGen (ComputerName,NumericValue) VALUES ('" + RegisterCode + "','" + NumericValue + "')";
                // "INSERT INTO SalesOrder(SONO) VALUES('" + SONO + "')";
                Conn.Open();
                cmd.ExecuteNonQuery();
                Conn.Close();
            }
            catch
            { }
        }
        #endregion





        //...............................................




        //public ArrayList GetUserAccessInfo()
        //{
        //    return UserAccess1;
        //}

        #region Get_Company_Name
        public void Get_Company_Name()
        {
            setConnectionString();
            try
            {
                string ConnString = ConnectionString;
                string sql = "select Company_Name,Autorize_Code from CheckR"; //where Company_Name ='" + CompanyName + "'";
                SqlConnection Conn = new SqlConnection(ConnString);
                SqlCommand cmd = new SqlCommand(sql);
                cmd.Connection = Conn;
                Conn.Open();
                SqlDataReader reader = cmd.ExecuteReader();


                if (reader.HasRows)
                {
                    while (reader.Read())
                    {
                        CompanyName = (reader.GetValue(0).ToString().Trim());
                        AutorizeCode = (reader.GetValue(1).ToString().Trim());
                    }
                }
                reader.Close();
                Conn.Close();

            }
            catch
            { }
            // }
            //catch
            //{ }
        }
        #endregion

        #region Get_Company_Name and serial number
        public void Get_Company_Name1()
        {
            setConnectionString();
            try
            {
                string ConnString = ConnectionString;
                string sql = "select CompanyName,SerialNumber from tblTempComData"; //where Company_Name ='" + CompanyName + "'";
                SqlConnection Conn = new SqlConnection(ConnString);
                SqlCommand cmd = new SqlCommand(sql);
                cmd.Connection = Conn;
                Conn.Open();
                SqlDataReader reader = cmd.ExecuteReader();


                if (reader.HasRows)
                {
                    while (reader.Read())
                    {
                        CompanyName1 = (reader.GetValue(0).ToString().Trim());
                        SerialNumber1 = (reader.GetValue(1).ToString().Trim());
                    }
                }
                reader.Close();
                Conn.Close();

            }
            catch
            { }
            // }
            //catch
            //{ }
        }
        #endregion




    }
}
